jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |-
            ./logger.sh Markdown-Blog & pid=$!
             iostat -d sda 1 >> logs/io.temp & iopid=$!
            cd Markdown-Blog
            git pull origin master
            npm i
            pm2 restart md-blog
             kill $iopid
             kill $pid
             cd ..
             ./io_logger.sh Markdown-Blog
          username: ${{ secrets.SSH_USERNAME }}
name: Continuous Deployment
'on':
  push:
    branches:
      - master
